nome=input("Digite um funcionário: ")
empresa=input("Digite a instituição: ")
qtd_funci=int(input("Digite a quantidade de funcionarios: "))
mediaMensalidade=float(input("Digite a media de mensalidade: "))
print(nome + " trabalha na empresa 5" + empresa)
print("Possui: " ,qtd_funci, "funcionarios.")
print("A média da mensalidade é de: " + str(mediaMensalidade))
print("=============verifique os tipos de dados abaixo==============")
print("O tipo de dado da variavel [nome] é: ", type(nome))
print("O tipo de dado da variavel [empresa] é: ", type(empresa))
print("O tipo de dado da variavel [qtd_funci] é: ", type(qtd_funci))
print("O tipo de dado da variavel [mediaMensalidade] é: ", type(mediaMensalidade))